This is a test file.
Is there any problem?
I dont think so!
Now it should throw exception at this line
